"""Parity suite: the SQL compiler (Compiler B) must reproduce the Arquero
executor's results (Compiler A) on identical data.

Goldens are generated by the REAL Arquero executor running headless in node —
packages/grammar/scripts/gen-parity-goldens.mjs — over the shared sample-data
CSVs. Regenerate them (after `pnpm build:toolkit`) whenever transformation
semantics change:

    node packages/grammar/scripts/gen-parity-goldens.mjs
"""

import json
import math
import os
import sys
from pathlib import Path

import pytest

from udiagent.query import (
    DuckDBConnector,
    QueryEngine,
    StarRocksConnector,
    UnsupportedQueryError,
)

_TESTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _TESTS_DIR.parents[2]
_SAMPLE_DATA = _REPO_ROOT / "sample-data"
_GOLDENS = json.loads((_TESTS_DIR / "goldens" / "parity.json").read_text())

# Opt-in second leg: run every parity case against a live StarRocks too
# (dev/starrocks/README.md). Seeds the golden CSVs into a `udi_parity`
# database on first use via the seed script.
_STARROCKS_ENABLED = os.getenv("UDI_STARROCKS_TEST") == "1"
_ENGINE_PARAMS = ["duckdb"] + (["starrocks"] if _STARROCKS_ENABLED else [])


def _starrocks_conn_args() -> dict:
    return {
        "host": os.getenv("UDI_STARROCKS_HOST", "127.0.0.1"),
        "port": int(os.getenv("UDI_STARROCKS_PORT", "9030")),
        "user": os.getenv("UDI_STARROCKS_USER", "root"),
        "password": os.getenv("UDI_STARROCKS_PASSWORD", ""),
    }


@pytest.fixture(scope="module", params=_ENGINE_PARAMS)
def engine(request):
    if request.param == "starrocks":
        sys.path.insert(0, str(_TESTS_DIR.parent / "scripts"))
        import seed_starrocks

        args = _starrocks_conn_args()
        entries = seed_starrocks.seed(
            _SAMPLE_DATA, "udi_parity", only=set(_GOLDENS["sources"]), **args
        )
        connector = StarRocksConnector(**args, database="udi_parity")
        return QueryEngine(
            connector, table_map={e["entity"]: e["table"] for e in entries}
        )
    views = {
        name: str(_SAMPLE_DATA / filename)
        for name, filename in _GOLDENS["sources"].items()
    }
    connector = DuckDBConnector(views=views)
    return QueryEngine(connector, table_map={name: name for name in views})


def _canon_value(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        f = float(value)
        if math.isnan(f):
            return None
        # Tolerance for float-representation drift between JS and SQL.
        return round(f, 6)
    return value


def _canon_rows(rows):
    """Order-independent, tolerance-normalized canonical form."""
    return sorted(
        tuple(sorted((k, _canon_value(v)) for k, v in row.items())) for row in rows
    )


@pytest.mark.parametrize(
    "case", _GOLDENS["cases"], ids=[c["name"] for c in _GOLDENS["cases"]]
)
def test_parity(engine, case):
    result = engine.run_query(
        source=case["spec"]["source"],
        transformation=case["spec"].get("transformation"),
        selections=case.get("selections"),
        display_data_only=case.get("displayDataOnly"),
    )

    assert _canon_rows(result["displayData"]) == _canon_rows(
        case["expect"]["displayData"]
    ), f"displayData mismatch for {case['name']}"

    assert result["isSubset"] == case["expect"]["isSubset"]

    if "extent" in result:
        assert _canon_rows(result["extent"]) == _canon_rows(
            case["expect"]["allData"]
        ), f"extent mismatch for {case['name']}"


def test_legacy_string_expressions_rejected(engine):
    with pytest.raises(UnsupportedQueryError):
        engine.run_query(
            source={"name": "penguins", "source": "penguins.csv"},
            transformation=[{"filter": "d['body_mass_g'] != null"}],
        )


def test_run_batch_isolates_per_viz_errors(engine):
    results = engine.run_batch(
        [
            {
                "vizId": "ok",
                "source": {"name": "penguins", "source": "penguins.csv"},
                "transformation": [
                    {"groupby": "species"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
            {
                "vizId": "bad",
                "source": {"name": "nope", "source": "nope.csv"},
            },
        ]
    )
    assert len(results["ok"]["displayData"]) == 3
    assert results["ok"]["aggregated"] is True
    assert "error" in results["bad"]


def test_cross_entity_selection_with_missing_field_errors_clearly(engine):
    """A brush that landed on an aggregated output column can't map back to
    the source table — the viz fails with an actionable message (and, via
    run_batch, without sinking the batch)."""
    results = engine.run_batch(
        [
            {
                "vizId": "bad",
                "source": {"name": "samples", "source": "samples.csv"},
                "transformation": [
                    {
                        "filter": {
                            "name": "sel",
                            "source": "donors",
                            "entityRelationship": {
                                "originKey": "hubmap_id",
                                "targetKey": "donor.hubmap_id",
                            },
                        }
                    },
                    {"groupby": "sample_category"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
            {
                "vizId": "ok",
                "source": {"name": "penguins", "source": "penguins.csv"},
                "transformation": [
                    {"groupby": "species"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
        ],
        selections={
            "sel": {
                "dataSourceKey": "donors",
                "selection": {"count donors": [1, 5]},  # aggregated output col
                "type": "interval",
            }
        },
    )
    assert "error" in results["bad"]
    assert "count donors" in results["bad"]["error"]
    assert len(results["ok"]["displayData"]) == 3, "batch not sunk"


def test_row_level_cap_and_truncation():
    views = {"penguins": str(_SAMPLE_DATA / "penguins.csv")}
    engine = QueryEngine(
        DuckDBConnector(views=views), table_map={"penguins": "penguins"}, row_cap=10
    )
    result = engine.run_query(
        source={"name": "penguins", "source": "penguins.csv"}
    )
    assert len(result["displayData"]) == 10
    assert result["truncated"] == {"cap": 10, "sampled": False}
    assert result["aggregated"] is False


def test_kde_structural():
    views = {"penguins": str(_SAMPLE_DATA / "penguins.csv")}
    engine = QueryEngine(DuckDBConnector(views=views), table_map={"penguins": "penguins"})
    result = engine.run_query(
        source={"name": "penguins", "source": "penguins.csv"},
        transformation=[
            {
                "filter": {
                    "op": "!=",
                    "left": {"field": "body_mass_g"},
                    "right": {"literal": None},
                }
            },
            {"groupby": "species"},
            {"kde": {"field": "body_mass_g", "samples": 50}},
        ],
    )
    rows = result["displayData"]
    assert result["aggregated"] is True
    species = {r["species"] for r in rows}
    assert species == {"Adelie", "Chinstrap", "Gentoo"}
    assert all("sample" in r and "density" in r for r in rows)
    assert len(rows) == 3 * 50
    # Densities integrate to ~1 per group.
    for s in species:
        pts = sorted((r["sample"], r["density"]) for r in rows if r["species"] == s)
        step = pts[1][0] - pts[0][0]
        integral = sum(d for _, d in pts) * step
        assert 0.9 < integral < 1.1
