"""Parity suite: the SQL compiler (Compiler B) must reproduce the Arquero
executor's results (Compiler A) on identical data.

Goldens are generated by the REAL Arquero executor running headless in node —
packages/grammar/scripts/gen-parity-goldens.mjs — over the shared sample-data
CSVs. Regenerate them (after `pnpm build:toolkit`) whenever transformation
semantics change:

    node packages/grammar/scripts/gen-parity-goldens.mjs
"""

import json
import math
import os
import sys
from pathlib import Path

import pytest

from udiagent.query import (
    DuckDBConnector,
    QueryEngine,
    StarRocksConnector,
    UnsupportedQueryError,
)

_TESTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _TESTS_DIR.parents[2]
_SAMPLE_DATA = _REPO_ROOT / "sample-data"
_GOLDENS = json.loads((_TESTS_DIR / "goldens" / "parity.json").read_text())

# Opt-in second leg: run every parity case against a live StarRocks too
# (dev/starrocks/README.md). Seeds the golden CSVs into a `udi_parity`
# database on first use via the seed script.
_STARROCKS_ENABLED = os.getenv("UDI_STARROCKS_TEST") == "1"
_ENGINE_PARAMS = ["duckdb"] + (["starrocks"] if _STARROCKS_ENABLED else [])


def _starrocks_conn_args() -> dict:
    return {
        "host": os.getenv("UDI_STARROCKS_HOST", "127.0.0.1"),
        "port": int(os.getenv("UDI_STARROCKS_PORT", "9030")),
        "user": os.getenv("UDI_STARROCKS_USER", "root"),
        "password": os.getenv("UDI_STARROCKS_PASSWORD", ""),
    }


@pytest.fixture(scope="module", params=_ENGINE_PARAMS)
def engine(request):
    if request.param == "starrocks":
        sys.path.insert(0, str(_TESTS_DIR.parent / "scripts"))
        import seed_starrocks

        args = _starrocks_conn_args()
        entries = seed_starrocks.seed(
            _SAMPLE_DATA, "udi_parity", only=set(_GOLDENS["sources"]), **args
        )
        connector = StarRocksConnector(**args, database="udi_parity")
        return QueryEngine(
            connector, table_map={e["entity"]: e["table"] for e in entries}
        )
    views = {
        name: str(_SAMPLE_DATA / filename)
        for name, filename in _GOLDENS["sources"].items()
    }
    connector = DuckDBConnector(views=views)
    return QueryEngine(connector, table_map={name: name for name in views})


def _canon_value(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        f = float(value)
        if math.isnan(f):
            return None
        # Tolerance for float-representation drift between JS and SQL.
        return round(f, 6)
    return value


def _sort_key(row):
    """Total order over canonicalized rows, tolerating mixed and null values.

    Sorting the raw tuples raises as soon as a column is nullable — `None < "a"`
    is a TypeError — so compare on the type name first and the repr second. Only
    used to make the comparison order-independent; the equality check itself is
    still on the values.
    """
    return tuple((type(v).__name__, repr(v)) for _, v in row)


def _canon_rows(rows):
    """Order-independent, tolerance-normalized canonical form.

    Null-valued keys are dropped rather than compared. The two executors represent
    "no value" differently at the edges — an all-null Arquero aggregate yields
    `undefined`, which JSON omits, where SQL emits an explicit NULL — and
    everything downstream (scales, filters, marks) treats absent and null alike.
    Comparing them would fail on a distinction no chart can observe.
    """
    return sorted(
        (
            tuple(
                sorted(
                    (k, _canon_value(v))
                    for k, v in row.items()
                    if _canon_value(v) is not None
                )
            )
            for row in rows
        ),
        key=_sort_key,
    )


@pytest.mark.parametrize(
    "case", _GOLDENS["cases"], ids=[c["name"] for c in _GOLDENS["cases"]]
)
def test_parity(engine, case):
    result = engine.run_query(
        source=case["spec"]["source"],
        transformation=case["spec"].get("transformation"),
        selections=case.get("selections"),
        display_data_only=case.get("displayDataOnly"),
    )

    assert _canon_rows(result["displayData"]) == _canon_rows(
        case["expect"]["displayData"]
    ), f"displayData mismatch for {case['name']}"

    assert result["isSubset"] == case["expect"]["isSubset"]

    if "extent" in result:
        assert _canon_rows(result["extent"]) == _canon_rows(
            case["expect"]["allData"]
        ), f"extent mismatch for {case['name']}"


def test_legacy_string_expressions_rejected(engine):
    with pytest.raises(UnsupportedQueryError):
        engine.run_query(
            source={"name": "penguins", "source": "penguins.csv"},
            transformation=[{"filter": "d['body_mass_g'] != null"}],
        )


def test_run_batch_isolates_per_viz_errors(engine):
    results = engine.run_batch(
        [
            {
                "vizId": "ok",
                "source": {"name": "penguins", "source": "penguins.csv"},
                "transformation": [
                    {"groupby": "species"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
            {
                "vizId": "bad",
                "source": {"name": "nope", "source": "nope.csv"},
            },
        ]
    )
    assert len(results["ok"]["displayData"]) == 3
    assert results["ok"]["aggregated"] is True
    assert "error" in results["bad"]


def test_cross_entity_selection_with_missing_field_errors_clearly(engine):
    """A brush that landed on an aggregated output column can't map back to
    the source table — the viz fails with an actionable message (and, via
    run_batch, without sinking the batch)."""
    results = engine.run_batch(
        [
            {
                "vizId": "bad",
                "source": {"name": "samples", "source": "samples.csv"},
                "transformation": [
                    {
                        "filter": {
                            "name": "sel",
                            "source": "donors",
                            "entityRelationship": {
                                "originKey": "hubmap_id",
                                "targetKey": "donor.hubmap_id",
                            },
                        }
                    },
                    {"groupby": "sample_category"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
            {
                "vizId": "ok",
                "source": {"name": "penguins", "source": "penguins.csv"},
                "transformation": [
                    {"groupby": "species"},
                    {"rollup": {"n": {"op": "count"}}},
                ],
            },
        ],
        selections={
            "sel": {
                "dataSourceKey": "donors",
                "selection": {"count donors": [1, 5]},  # aggregated output col
                "type": "interval",
            }
        },
    )
    assert "error" in results["bad"]
    assert "count donors" in results["bad"]["error"]
    assert len(results["ok"]["displayData"]) == 3, "batch not sunk"


def test_row_level_cap_and_truncation():
    views = {"penguins": str(_SAMPLE_DATA / "penguins.csv")}
    engine = QueryEngine(
        DuckDBConnector(views=views), table_map={"penguins": "penguins"}, row_cap=10
    )
    result = engine.run_query(
        source={"name": "penguins", "source": "penguins.csv"}
    )
    assert len(result["displayData"]) == 10
    assert result["truncated"] == {"cap": 10, "sampled": False}
    assert result["aggregated"] is False


def test_offset_pages_row_level_results():
    """`offset` windows row-level results deterministically when the spec
    orders by a UNIQUE key (tie order is otherwise unspecified in SQL —
    same caveat as rolling windows)."""
    views = {"donors": str(_SAMPLE_DATA / "donors.csv")}
    engine = QueryEngine(
        DuckDBConnector(views=views), table_map={"donors": "donors"}, row_cap=100
    )
    spec = {
        "source": {"name": "donors", "source": "donors.csv"},
        "transformation": [
            {"orderby": [{"field": "hubmap_id", "order": "asc"}]},
        ],
    }
    first = engine.run_query(**spec)
    assert len(first["displayData"]) == 100
    assert first["truncated"] == {"cap": 100, "sampled": False}

    second = engine.run_query(**spec, offset=100)
    assert len(second["displayData"]) == 100
    assert second["displayData"][0] != first["displayData"][0]

    # Windows must tile the full ordered result: page1+page2 == first 200.
    full = QueryEngine(
        DuckDBConnector(views=views), table_map={"donors": "donors"}, row_cap=400
    ).run_query(**spec)
    assert first["displayData"] + second["displayData"] == full["displayData"][:200]

    # Last window: donors has 266 rows -> offset 250 yields 16, untruncated.
    tail = engine.run_query(**spec, offset=250)
    assert len(tail["displayData"]) == 16
    assert "truncated" not in tail

    # run_batch forwards offset.
    batch = engine.run_batch([{"vizId": "q", **spec, "offset": 250}], selections=None)
    assert len(batch["q"]["displayData"]) == 16


def test_cube_template_marginal_filter_runs_in_sql(tmp_path):
    """A data-cube template must execute in server-side SQL mode: the
    <MARGINAL> resolver has to emit a structured Expr && -chain, not a raw
    Arquero string (which the compiler rejects — see
    test_legacy_string_expressions_rejected). Guards against that regressing.
    """
    import json

    from udiagent import vis_generate as vg
    from udiagent.schema import parse_schema_from_dict

    # Tiny powerset cube: grand total, 1D marginals, and a 2D cell. A 1D
    # gender marginal must select exactly the gender!=null, class==null rows.
    csv = tmp_path / "cube.csv"
    csv.write_text(
        "gender,class_display,cnt\n"
        ",,100\n"
        "M,,60\n"
        "F,,40\n"
        ",inpatient,70\n"
        ",outpatient,30\n"
        "M,inpatient,45\n"
    )
    schema = parse_schema_from_dict(
        {
            "udi:path": "",
            "resources": [
                {
                    "name": "cube",
                    "path": str(csv),
                    "udi:cube": True,
                    "udi:dimensions": ["gender", "class_display"],
                    "udi:measures": ["cnt"],
                    "schema": {
                        "fields": [
                            {"name": "gender", "udi:data_type": "nominal"},
                            {"name": "class_display", "udi:data_type": "nominal"},
                            {"name": "cnt", "udi:data_type": "quantitative"},
                        ]
                    },
                }
            ],
        }
    )

    tpls = json.loads(
        (
            _REPO_ROOT
            / "packages/agent/src/udiagent/data/skills/template_visualizations.json"
        ).read_text()
    )
    cube_bar = next(t for t in tpls if t.get("tags") == ["data_cube", "barchart"])
    spec = vg.instantiate_template(
        cube_bar["spec_template"], {"E": "cube", "D": "gender"}, schema
    )

    marginal = spec["transformation"][0]["filter"]
    assert isinstance(marginal, dict), "MARGINAL must resolve to a structured Expr"

    engine = QueryEngine(
        DuckDBConnector(views={"cube": str(csv)}), table_map={"cube": "cube"}
    )
    result = engine.run_query(
        source=spec["source"], transformation=spec["transformation"]
    )
    rows = {(r["gender"], r["cnt"]) for r in result["displayData"]}
    assert rows == {("M", 60), ("F", 40)}


def test_grouped_cdf_output_is_render_stable():
    """A grouped CDF (group -> ordered rolling percentile) must come out ordered
    so each group's line renders monotonically. The rolling frame emits several
    percentiles at a tied x; a final `orderby(percentile)` keeps them ascending
    in output order (otherwise the line draws downward jags). Guards the CDF
    template's ordering. Also exercises multi-field orderby ({field: [list]})."""
    views = {"penguins": str(_SAMPLE_DATA / "penguins.csv")}
    engine = QueryEngine(DuckDBConnector(views=views), table_map={"penguins": "penguins"})
    result = engine.run_query(
        source={"name": "penguins", "source": "penguins"},
        transformation=[
            {"filter": {"op": "!=", "left": {"field": "bill_depth_mm"}, "right": {"literal": None}}},
            {"groupby": "species"},
            {"orderby": {"field": "bill_depth_mm", "order": "asc"}},
            {"derive": {"total": {"agg": "count"}}},
            {"derive": {"percentile": {"rolling": {"expression": {
                "op": "/", "left": {"agg": "count"}, "right": {"field": "total"}}}}}},
            {"orderby": {"field": "percentile", "order": "asc"}},
        ],
    )
    per_group: dict = {}
    for row in result["displayData"]:
        per_group.setdefault(row["species"], []).append((row["bill_depth_mm"], row["percentile"]))
    for species, pts in per_group.items():
        # output order must be non-decreasing in BOTH x and percentile per group
        assert all(pts[i][0] >= pts[i - 1][0] - 1e-9 for i in range(1, len(pts))), species
        assert all(pts[i][1] >= pts[i - 1][1] - 1e-9 for i in range(1, len(pts))), species
        assert abs(pts[-1][1] - 1.0) < 1e-9, f"{species} CDF should end at 1.0"

    # {field: [list]} multi-field orderby must compile (was an AttributeError).
    multi = engine.run_query(
        source={"name": "penguins", "source": "penguins"},
        transformation=[{"orderby": {"field": ["species", "bill_depth_mm"], "order": "asc"}}],
    )
    assert len(multi["displayData"]) > 0


def test_kde_structural():
    views = {"penguins": str(_SAMPLE_DATA / "penguins.csv")}
    engine = QueryEngine(DuckDBConnector(views=views), table_map={"penguins": "penguins"})
    result = engine.run_query(
        source={"name": "penguins", "source": "penguins.csv"},
        transformation=[
            {
                "filter": {
                    "op": "!=",
                    "left": {"field": "body_mass_g"},
                    "right": {"literal": None},
                }
            },
            {"groupby": "species"},
            {"kde": {"field": "body_mass_g", "samples": 50}},
        ],
    )
    rows = result["displayData"]
    assert result["aggregated"] is True
    species = {r["species"] for r in rows}
    assert species == {"Adelie", "Chinstrap", "Gentoo"}
    assert all("sample" in r and "density" in r for r in rows)
    assert len(rows) == 3 * 50
    # Densities integrate to ~1 per group.
    for s in species:
        pts = sorted((r["sample"], r["density"]) for r in rows if r["species"] == s)
        step = pts[1][0] - pts[0][0]
        integral = sum(d for _, d in pts) * step
        assert 0.9 < integral < 1.1
