#!/usr/bin/env python
"""Generate the agent's env-var docs from ServerConfig — the single source.

`ServerConfig` (src/udiagent/server/config.py) carries a description, default,
and optional example for every variable, so this renders both places that used
to be hand-maintained (and had already drifted apart):

  * `packages/agent/.env.template`  — the whole file
  * `packages/agent/README.md`      — the table between the generated markers

Usage::

    python scripts/gen_env_docs.py            # write
    python scripts/gen_env_docs.py --check    # exit 1 if out of date (CI)
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

_AGENT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_AGENT_ROOT / "src"))

from udiagent.server.config import ServerConfig  # noqa: E402

TEMPLATE_PATH = _AGENT_ROOT / ".env.template"
README_PATH = _AGENT_ROOT / "README.md"

BEGIN = "<!-- BEGIN generated: env vars (scripts/gen_env_docs.py) -->"
END = "<!-- END generated: env vars -->"

HEADER = """\
# Generated by scripts/gen_env_docs.py from ServerConfig — do not edit by hand.
# Describe a variable in src/udiagent/server/config.py and regenerate.
#
# Copy to .env (scripts/setup.mjs does this for you). Values here are the
# defaults; uncomment a line only to change one.
"""


def _extra(field, key):
    extra = field.json_schema_extra or {}
    return extra.get(key)


def _template_value(field):
    """The value a commented-out template line should illustrate."""
    if field.examples:
        return field.examples[0]
    default = field.default
    if default is None or default == "":
        return ""
    if isinstance(default, bool):
        return "1" if default else "0"
    if isinstance(default, float) and default.is_integer():
        return str(int(default))
    return str(default)


def _readme_default(field):
    default = field.default
    if default is None or default == "":
        return "—"
    if isinstance(default, bool):
        return "`1`" if default else "`0`"
    if isinstance(default, float) and default.is_integer():
        return f"`{int(default)}`"
    return f"`{default}`"


def render_template() -> str:
    out = [HEADER]
    group = None
    for name, field in ServerConfig.model_fields.items():
        if (new_group := _extra(field, "group")) and new_group != group:
            group = new_group
            out.append(f"\n# === {group} ===\n")
        out.append("\n")
        # break_on_hyphens=False keeps `X-OpenAI-Key` and friends intact.
        for line in textwrap.wrap(
            field.description, width=76, break_on_hyphens=False
        ):
            out.append(f"# {line}\n")
        key = name.upper()
        # A variable the developer must actually look at is left live; the rest
        # are commented so the file documents without overriding any default.
        live = _extra(field, "template")
        if live is not None:
            out.append(f"{key}={live}\n")
        else:
            out.append(f"# {key}={_template_value(field)}\n")
    return "".join(out)


def _markdown_table(header: list[str], rows: list[list[str]]) -> str:
    """Emit the column padding prettier would apply anyway.

    The repo's husky/lint-staged hook runs prettier over staged markdown, so an
    unpadded table would be reformatted on commit and `--check` would then
    report drift on the very next CI run.
    """
    widths = [
        max(len(header[i]), *(len(row[i]) for row in rows))
        for i in range(len(header))
    ]

    def line(cells: list[str]) -> str:
        padded = " | ".join(
            cell.ljust(width) for cell, width in zip(cells, widths)
        )
        return f"| {padded} |"

    return "\n".join(
        [line(header), line(["-" * width for width in widths])]
        + [line(row) for row in rows]
    )


def render_readme_table() -> str:
    return _markdown_table(
        ["Variable", "Default", "Description"],
        [
            [
                f"`{name.upper()}`",
                _readme_default(field),
                " ".join(field.description.split()),
            ]
            for name, field in ServerConfig.model_fields.items()
        ],
    )


def splice_readme(text: str, table: str) -> str:
    start, end = text.index(BEGIN), text.index(END)
    return text[: start + len(BEGIN)] + f"\n\n{table}\n\n" + text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the generated docs are out of date",
    )
    args = parser.parse_args()

    wanted = {
        TEMPLATE_PATH: render_template(),
        README_PATH: splice_readme(
            README_PATH.read_text(), render_readme_table()
        ),
    }

    stale = [p for p, content in wanted.items() if p.read_text() != content]
    if args.check:
        for path in stale:
            print(f"out of date: {path.relative_to(_AGENT_ROOT.parents[1])}")
        if stale:
            print(
                "\nServerConfig changed without regenerating. Run:\n"
                "  uv run --project packages/agent python "
                "packages/agent/scripts/gen_env_docs.py"
            )
            return 1
        print("env docs are up to date")
        return 0

    for path in stale:
        path.write_text(wanted[path])
        print(f"wrote {path.relative_to(_AGENT_ROOT.parents[1])}")
    if not stale:
        print("env docs already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
