/// <reference types="vite/client" />

// Generated by scripts/gen-chat-env-docs.mjs from src/app/envVars.ts —
// do not edit by hand. Describe a variable there and regenerate.

interface ImportMetaEnv {
  /**
   * UDIAgent FastAPI server URL. May also be a same-origin path (e.g.
   * `/api/yac`) when the chat sits behind the host app’s reverse proxy.
   */
  readonly VITE_UDI_API_BASE_URL?: string;
  /**
   * Path or URL to a `datapackage.json`. Defaults to the bundled HuBMAP
   * snapshot synced from `sample-data/`. Ignored when
   * `VITE_UDI_REMOTE_PACKAGE` is set.
   */
  readonly VITE_UDI_DATA_PACKAGE?: string;
  /**
   * Name of a server-side data package (configured on the agent via
   * `UDI_QUERY_BACKENDS`). When set, no CSVs load in the browser: metadata
   * comes from `/v1/yac/metadata` and queries go to `/v1/yac/query`. Takes
   * precedence over `VITE_UDI_DATA_PACKAGE`.
   */
  readonly VITE_UDI_REMOTE_PACKAGE?: string;
  /**
   * Prompt the user for an OpenAI key in the UI. Defaults to `true`, but
   * `.env.example` ships `false` because local dev runs against an agent
   * that has its own `OPENAI_API_KEY`.
   */
  readonly VITE_UDI_REQUIRE_API_KEY?: string;
  /**
   * LLM model override. Sent **only when the user supplies their own OpenAI
   * key** — the agent honors a requested model only alongside an
   * `X-OpenAI-Key`, so whoever pays for the tokens picks the model.
   * Otherwise the agent’s `GPT_MODEL_NAME` applies.
   */
  readonly VITE_UDI_MODEL?: string;
  /**
   * Start in read-only mode: the chat collapses to a rail and every editing
   * control (card drag, resize, rename, close, field tweak, grid settings,
   * session import) is hidden, while brushing, filters, the table toggle and
   * downloads stay. `true` leaves an Explore Data button over the dashboard
   * (and one on the rail) that opens the chat; `locked` removes both. With
   * the chat collapsed there is nothing to build a dashboard from, so pair
   * this with `VITE_UDI_INITIAL_SESSION`.
   */
  readonly VITE_UDI_READ_ONLY?: string;
  /**
   * Path or URL to a session export — the JSON written by the dashboard’s
   * `Session → Export session` action. Fetched at startup and used to seed
   * the dashboard and the conversation behind it. Anything under `public/`
   * is served from the site root, so `public/demo-session.json` is
   * `/demo-session.json`. A malformed file fails loudly through the
   * ErrorBoundary; a missing one only logs, and the dashboard starts empty.
   */
  readonly VITE_UDI_INITIAL_SESSION?: string;
  /**
   * Public base path for the built SPA (read in `vite.config.ts`, build-time
   * only). The library build always uses `./`.
   */
  readonly VITE_BASE?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
