/// <reference types="vite/client" />

// Generated by scripts/gen-chat-env-docs.mjs from src/app/envVars.ts —
// do not edit by hand. Describe a variable there and regenerate.

interface ImportMetaEnv {
  /**
   * UDIAgent FastAPI server URL. May also be a same-origin path (e.g.
   * `/api/yac`) when the chat sits behind the host app’s reverse proxy.
   */
  readonly VITE_UDI_API_BASE_URL?: string;
  /**
   * Path or URL to a `datapackage.json`. Defaults to the bundled HuBMAP
   * snapshot synced from `sample-data/`. Ignored when
   * `VITE_UDI_REMOTE_PACKAGE` is set.
   */
  readonly VITE_UDI_DATA_PACKAGE?: string;
  /**
   * Name of a server-side data package (configured on the agent via
   * `UDI_QUERY_BACKENDS`). When set, no CSVs load in the browser: metadata
   * comes from `/v1/yac/metadata` and queries go to `/v1/yac/query`. Takes
   * precedence over `VITE_UDI_DATA_PACKAGE`.
   */
  readonly VITE_UDI_REMOTE_PACKAGE?: string;
  /**
   * Prompt the user for an OpenAI key in the UI. Defaults to `true`, but
   * `.env.example` ships `false` because local dev runs against an agent
   * that has its own `OPENAI_API_KEY`.
   */
  readonly VITE_UDI_REQUIRE_API_KEY?: string;
  /**
   * LLM model override. Sent **only when the user supplies their own OpenAI
   * key** — the agent honors a requested model only alongside an
   * `X-OpenAI-Key`, so whoever pays for the tokens picks the model.
   * Otherwise the agent’s `GPT_MODEL_NAME` applies.
   */
  readonly VITE_UDI_MODEL?: string;
  /**
   * Public base path for the built SPA (read in `vite.config.ts`, build-time
   * only). The library build always uses `./`.
   */
  readonly VITE_BASE?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
